### ISSUE TITLE
Using large sliderStyle

### ISSUE THREAD

**Issue by yeonkim** [Esri/bootstrap-map-js#134] opened 2014-11-11 15:00 UTC
Hello,

I want to use large slider that shows zoom levels, not the small one that only has +/- buttons.

When I create a map using BootstrapMap.create like below, I still get a small slider. How can I get a large slider?

	var map = BootstrapMap.create("mapDiv",{
	  sliderStyle: "large",
	  extent:extent,
	  logo:false,
	  scrollWheelZoom: true
	}); 

If I create a map using esri/map with the same options (map parameters), large slider does show up. Thank you for your hep.

Yeon

**Comment by alaframboise** [comment] 2015-04-29 15:41
The issue is that the samples use <script src="//js.arcgis.com/3.13compact"></script> and you need to use <script src="//js.arcgis.com/3.13"></script> to pull in the full library set to get the large slider. There are tonnes of CSS clashes that would need to be addressed however. Closing for now unless this becomes high demand.

**Closed by alaframboise** 2015-04-29 15:41 UTC
